config/routes.rb
Rails.application.routes.draw do
  get 'admins/new'

  devise_for :admins
  root 'home#index'

  namespace :admin do
    resources :rooms do
      resources :recorders
    end
  end

  resources :admins
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication?
    true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :recorder

  validates :measure, :time, presence: true

  scope :by_created_at, -> { order(:created_at) }
  scope :for_a_day, -> (day) { where("time >= :start AND time <= :end", start: day.beginning_of_day, end: day.end_of_day) }
end

app/models/recorder.rb
class Recorder < ApplicationRecord
  belongs_to :room
  has_many :measurements, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :position_x, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: Proc.new { |r| r.room.dimension_x } }
  validates :position_y, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: Proc.new { |r| r.room.dimension_y } }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :recorders, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :dimension_x, :dimension_y, presence: true, numericality: { greater_than: 0 }

  def measures_per_days_chart(date = 'today')
    day = if date == 'today'
            Date.today
          elsif date == 'yesterday'
            Date.yesterday
          else
            Date.parse(date)
          end

    measures = Hash.new(0)

    recorders.each do |recorder|
      recorder.measurements.for_a_day(day).each do |measurement|
        measures[measurement.time.to_i] += measurement.measure
      end
    end

    measures.values.map { |measure| measure / recorders.count }
  end

  def coordinates_per_room_chart
    coordinates = Array.new

    (0...dimension_x).each do |x|
      (0...dimension_y).each do |y|
        coordinates << [x, y, 0]
      end
    end
    add_recorders_to_chart(coordinates)
  end

  private

  def add_recorders_to_chart(coordinates)
    x, y = 0, 0

    recorders.each do |recorder|
      x = recorder.position_x
      y = recorder.position_y
      coordinates << [x, y, 10]
    end
    coordinates
  end
end

app/controllers/admin/recorders_controller.rb
class Admin::RecordersController < ApplicationController
  expose(:room, id: :room_id)

  expose(:recorders) { room.recorders.where.not(id: nil) }
  expose(:recorder, attributes: :recorder_params, parent: :room)

  def create
    if recorder.save
      redirect_to admin_room_path(room), notice: 'Recorder created successfully'
    else
      render '/admin/rooms/show'
    end
  end

  def destroy
    recorder.destroy

    redirect_to admin_room_path(room)
  end

  private
  def recorder_params
    params.require(:recorder).permit(:name, :position_x, :position_y)
  end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :authenticate_admin!

  expose :rooms, -> { Room.all }
  expose :room

  expose :recorders do
    room.recorders.where.not(id: nil)
  end
  expose :recorder, -> { Recorder.new  }

  def create
    if room.save
      redirect_to admin_room_path(room)
    else
      render :new
    end
  end

  def update
    if room.update(room_params)
      redirect_to admin_room_path(room)
    else
      render :edit
    end
  end

  def destroy
    room.destroy

    redirect_to admin_rooms_path
  end

  private
  def room_params
    params.require(:room).permit(:name, :dimension_x, :dimension_y)
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  expose :admins, -> { Admin.all }
  expose :admin

  def create
    if admin.save
      redirect_to admin_path(admin)
    else
      render :new
    end
  end

  def update
    if admin.update(admin_params)
      redirect_to admin_path(admin)
    else
      render :edit
    end
  end

  def destroy
    admin.destroy
    redirect_to admins_path
  end

  private

  def admin_params
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose :rooms, -> { Room.all }
  expose :date, -> { params[:date] || 'today' }
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def default_date(date)
    if date == 'today'
      Date.today
    elsif date == 'yesterday'
      Date.today - 1
    else
      Date.parse(date)
    end
  end
end

app/helpers/recorders_helper.rb
module RecordersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/recorders/_form.html.erb
<%= simple_form_for [:admin, room, recorder] do |f| %>
  <%= f.input :name %>
  <%= f.input :position_x %>
  <%= f.input :position_y %>
  <%= f.button :submit %>
<% end %>

app/views/admin/rooms/_form.html.erb
<%= simple_form_for [:admin, room] do |f| %>
  <%= f.input :name %>
  <%= f.input :dimension_x %>
  <%= f.input :dimension_y %>
  <%= f.button :submit %>
<% end %>

app/views/admin/rooms/edit.html.erb
<h1>Edit room</h1>
<%= render 'form' %>
<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/index.html.erb
<h1>Sound Dashboard</h1>
<h2>Rooms</h2>

<ul>
  <% rooms.each do |room| %>
    <li>
      <%= room.name %>
      <%= link_to 'Show', admin_room_path(room) %>
      <%= link_to 'Edit', edit_admin_room_path(room) %>
      <%= link_to 'Delete', admin_room_path(room), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'New room', new_admin_room_path(room) %>
<%= link_to 'Admins', admins_path %>

app/views/admin/rooms/new.html.erb
<h1>New room</h1>
<%= render 'form' %>
<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/show.html.erb
<h1>Room</h1>
<p>
  <strong>Name:</strong>
  <%= room.name %>
</p>
<p>
  <strong>Dimensions:</strong>
  <%= room.dimension_x %>x<%= room.dimension_y %>
</p>

<%= link_to 'Edit', edit_admin_room_path(room) %>

<% recorders.each do |recorder| %>
  <p>
    <strong>Recorder:</strong>
    <%= recorder.name %> <%= recorder.position_x %>x<%= recorder.position_y %>
    <%= link_to 'Delete', admin_room_recorder_path(room, recorder), method: :delete %>
  </p>
<% end %>

<h2>New recorder</h2>
<%= render 'admin/recorders/form' %>

<%= link_to 'Back', admin_rooms_path %>

app/views/admins/_form.html.erb
<%= simple_form_for admin do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

app/views/admins/edit.html.erb
<h1>Edit admin</h1>
<%= render 'form' %>
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Sound Dashboard</h1>
<h2>Admins</h2>

<ul>
  <% admins.each do |admin| %>
    <li>
      <%= admin.email %>
      <%= link_to 'Show', admin_path(admin) %>
      <%= link_to 'Edit', edit_admin_path(admin) %>
      <%= link_to 'Delete', admin_path(admin), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'New admin', new_admin_path(admin) %>
<%= link_to 'Back', admin_rooms_path %>

app/views/admins/new.html.erb
<h1>New user</h1>
<%= render 'form' %>
<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<h1>Admin</h1>
<p>
  <strong>Email:</strong>
  <%= admin.email %>
</p>

<%= link_to 'Edit', edit_admin_path %>
<%= link_to 'Back', admins_path %>

app/views/home/_chart.html.erb
<% @rooms.each do |room| %>
  <script>
    $(function () {
      $("#<%= room.id %>").highcharts({
        chart: {
          type: 'spline'
        },

        title: {
          text: "<%= room.name %>"
        },

        xAxis: {
          type: 'datetime',
          labels: {
            overflow: 'justify'
          }
        },

        yAxis: {
          title: {
            text: 'decibels'
          },
        },

        tooltip: {
          valueSuffix: ' dB'
        },

        plotOptions: {
          spline: {
            lineWidth: 4,
            states: {
              hover: {
                lineWidth: 5
              }
            },

            marker: {
              enabled: false
            },

            pointInterval: 300000, // five minutes
            pointStart: Date.UTC(2016, 8, 5, 8, 0, 0)
          }
        },

        series: [{
          name: "<%= room.name %>",
          data: <%= room.measures_per_days_chart %>
      }],

        navigation: {
          menuItemStyle: {
            fontSize: '10px'
          }
        }
      });
    });
  </script>

  <div id="<%= room.id %>"></div>
<% end %>

app/views/home/_day_chart.html.erb
<% rooms.each do |room| %>
  <script>
    $(function () {
      $("#<%= room.id %>").highcharts({
        chart: {
          type: 'spline'
        },

        title: {
          text: "<%= room.name %>"
        },

        xAxis: {
          type: 'datetime',
          labels: {
            overflow: 'justify'
          }
        },

        yAxis: {
          title: {
            text: 'decibels'
          },
        },

        tooltip: {
          valueSuffix: ' dB'
        },

        plotOptions: {
          spline: {
            lineWidth: 4,
            states: {
              hover: {
                lineWidth: 5
              }
            },

            marker: {
              enabled: false
            },

            pointInterval: 300000, // five minutes
            pointStart: Date.UTC(2016, 8, 5, 8, 0, 0)
          }
        },

        series: [{
          name: "<%= room.name %>",
          data: <%= room.measures_per_days_chart(date) %>
      }],

        navigation: {
          menuItemStyle: {
            fontSize: '10px'
          }
        }
      });
    });
  </script>

  <div id="<%= room.id %>"></div>
<% end %>

app/views/home/_heat_map.html.erb
<% rooms.each do |room| %>
  <script>
    $(function () {
      $("#h<%= room.id %>").highcharts({
        chart: {
          type: 'heatmap',
          marginTop: 40,
          marginBottom: 80,
          plotBorderWidth: 1

        },

        title: {
      text: "<%= room.name %>"

    },

    xAxis: {
      categories: <%= (1..room.dimension_x).to_a %>

    },

    yAxis: {
      categories: <%= (1..room.dimension_y).to_a %>,
      title: null

    },

    colorAxis: {
      min: 0,
      minColor: '#FFFFFF',
      maxColor: Highcharts.getOptions().colors[0]

    },

    legend: {
      align: 'right',
      layout: 'vertical',
      margin: 0,
      verticalAlign: 'top',
      y: 25,
      symbolHeight: 280

    },

    tooltip: {
      formatter: function () {
        return '<b>' + this.series.xAxis.categories[this.point.x] + '</b>x<b>' + this.series.yAxis.categories[this.point.y] + '</b>: <b>' + this.point.value + '</b><br>'

      }

    },

    series: [{
      name: "#<%= room.name %>",
      borderWidth: 1,
      data: <%= room.coordinates_per_room_chart %>,
      dataLabels: {
        enabled: true,
        color: '#000000'

      }

    }]

  });

});
  </script>

  <div id="h<%= room.id %>"></div>
<% end %>

app/views/home/index.html.erb
<h1>Sound Dashboard</h1>

<%= form_tag(root_path, method: :get) do %>
  <%= date_field_tag 'date', default_date(date) %>
  <%= submit_tag 'Select' %>
<% end %>

<%= link_to 'Yesterday', root_path(date: 'yesterday') %>
<%= link_to 'Today', root_path(date: 'today') %>

<%= render partial: 'day_chart', locals: { date: date } %>
<%= render 'heat_map' %>

<%= link_to 'Sign in', admin_rooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoundDashboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= notice %></p>
    <p><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>